import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Video Transcription",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={"bg-gradient-to-r from-fuchsia-500 to-cyan-500"}>{children}</body>
    </html>
  );
}
